import UIKit

extension UIColor {
    static let ypBlack = UIColor(named: "ypBlack")
    static let ypWhite = UIColor(named: "ypWhite")
    static let ypGray = UIColor(named: "ypGray")
    static let ypBackground = UIColor(named: "ypBackground")
    static let ypBlue = UIColor(named: "ypBlue")
    static let ypRed = UIColor(named: "ypRed")
    static let ypSelection1 = UIColor(named: "ypSelection1")
    static let ypSelection2 = UIColor(named: "ypSelection2")
    static let ypSelection3 = UIColor(named: "ypSelection3")
    static let ypSelection4 = UIColor(named: "ypSelection4")
    static let ypSelection5 = UIColor(named: "ypSelection5")
    static let ypSelection6 = UIColor(named: "ypSelection6")
    static let ypSelection7 = UIColor(named: "ypSelection7")
    static let ypSelection8 = UIColor(named: "ypSelection8")
    static let ypSelection9 = UIColor(named: "ypSelection9")
    static let ypSelection10 = UIColor(named: "ypSelection10")
    static let ypSelection11 = UIColor(named: "ypSelection11")
    static let ypSelection12 = UIColor(named: "ypSelection12")
    static let ypSelection13 = UIColor(named: "ypSelection13")
    static let ypSelection14 = UIColor(named: "ypSelection14")
    static let ypSelection15 = UIColor(named: "ypSelection15")
    static let ypSelection16 = UIColor(named: "ypSelection16")
    static let ypSelection17 = UIColor(named: "ypSelection17")
    static let ypSelection18 = UIColor(named: "ypSelection18")
}
